name: 🐞 Bug
description: File a bug/issue
title: "<title>"
labels: ["bug"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Bug description
    description: A concise description of what went wrong
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1.
      2.
      3.
  validations:
    required: true
- type: textarea
  attributes:
    label: Environment including version:
    description: |
      examples:
        - **Beesy**: v0.0.11 (get version from: chrome://extensions/?id=eabicnldgjknbifdgmnieblkbnggfnde)
        - **OS**: macOS Ventura 13.4.1
        - **Browser**: Google Chrome v115.0.5790.170 (Official Build) (arm64)
        - **Media Player**: VLC v3.0.18 Vetinari (Intel 64bit)
    value: |
        - OS:
        - Browser:
        - Media Player:
    render: Markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: Attachments
    description: |
      Include screenshots, logs or video recording (created using Beesy) here.
      Please remove any sensitive information that you wouldn't want to share publicly.

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
